build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
labels:
  io.hass.type: addon
  org.opencontainers.image.source: https://github.com/ulstrup90210/home-assistant-grok-addons
