build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
labels:
  io.hass.type: addon
  org.opencontainers.image.source: https://github.com/ulstrup90210/home-assistant-grok-addons
